version: '3'

services:
  app:
    container_name: wallet_app
    volumes:
      - ./app:/app/
    build: .
    ports:
      - "8000:8000"
    env_file:
      - dev.env

  db:
    image: postgres:14.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    container_name: wallet_db
    env_file:
      dev.env
